repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "ffb6a75"
    hooks:
      - id: prettier
        files: ^ui/
        types_or: [css, javascript, html, json]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.56.0"
    hooks:
      - id: eslint
        files: ^ui/
        args: [-c, ui/.eslintrc.json]
